flowchart TD
  n_movies["movies"]
  n_movie_details["movie-details"]
  n_player["player"]
  n_movie_details_restored["movie-details-restored"]
  n_movies_restored["movies-restored"]
  n_movies -->|click| n_movie_details
  n_movie_details -->|click| n_player
  n_player -->|back| n_movie_details_restored
  n_movie_details_restored -->|back| n_movies_restored
