#!/usr/bin/env python3
from pathlib import Path
import sys
root=Path(sys.argv[1])

def rep(path, old, new, label):
 p=root/path; s=p.read_text()
 if new in s: return
 if old not in s: raise SystemExit(f'missing {label}')
 p.write_text(s.replace(old,new,1))

rep('app/build.gradle.kts','versionCode = 47','versionCode = 48','versionCode')
rep('app/build.gradle.kts','versionName = "0.9.3.3"','versionName = "0.9.3.4"','versionName')
main='app/src/main/java/sa/hulksa/player/ui/screens/MainShellScreen.kt'
rep(main,'import androidx.compose.runtime.remember\n','import androidx.compose.runtime.remember\nimport androidx.compose.runtime.snapshotFlow\n','snapshotFlow import')
rep(main,'    var previousDestination by remember { mutableStateOf(state.destination) }\n    LaunchedEffect(state.destination) {\n        if (previousDestination != state.destination) {\n            queryMemory[previousDestination] = state.searchQuery\n            categoryMemory[previousDestination] = state.selectedCategoryId\n            val restoredQuery = queryMemory[state.destination].orEmpty()\n            val restoredCategory = categoryMemory[state.destination]\n            if (state.searchQuery != restoredQuery) onSearch(restoredQuery)\n            if (state.selectedCategoryId != restoredCategory) onSelectCategory(restoredCategory)\n            previousDestination = state.destination\n        }\n    }\n','    var previousDestination by remember { mutableStateOf(state.destination) }\n    val rememberingSelectDestination: (MainDestination) -> Unit = { destination ->\n        queryMemory[state.destination] = state.searchQuery\n        categoryMemory[state.destination] = state.selectedCategoryId\n        onSelectDestination(destination)\n    }\n    LaunchedEffect(state.destination) {\n        if (previousDestination != state.destination) {\n            val restoredQuery = queryMemory[state.destination].orEmpty()\n            val restoredCategory = categoryMemory[state.destination]\n            if (state.searchQuery != restoredQuery) onSearch(restoredQuery)\n            if (state.selectedCategoryId != restoredCategory) onSelectCategory(restoredCategory)\n            previousDestination = state.destination\n        }\n    }\n','destination memory wrapper')
rep(main,'                    onSelect = onSelectDestination,','                    onSelect = rememberingSelectDestination,','rail memory nav')
rep(main,'                MobileNavigation(state.destination, onSelectDestination)','                MobileNavigation(state.destination, rememberingSelectDestination)','mobile memory nav')
rep(main,'                        onSelectDestination = onSelectDestination,','                        onSelectDestination = rememberingSelectDestination,','content memory nav tv')
rep(main,'                        onSelectDestination = onSelectDestination,','                        onSelectDestination = rememberingSelectDestination,','content memory nav mobile')
rep(main,'            .pointerInput(category.id, moving) {\n                if (moving) {\n                    detectHorizontalDragGestures(\n                        onDragStart = { dragAccumulator = 0f },\n                        onDragCancel = { dragAccumulator = 0f },\n                        onDragEnd = { dragAccumulator = 0f },\n                    ) { change, dragAmount ->\n                        change.consume()\n                        dragAccumulator += dragAmount\n                        while (dragAccumulator >= 24f) { onMoveRight(); dragAccumulator -= 24f }\n                        while (dragAccumulator <= -24f) { onMoveLeft(); dragAccumulator += 24f }\n                    }\n                } else {\n                    detectTapGestures(onLongPress = { onLongClick() })\n                }\n            }\n','            .pointerInput(category.id) {\n                detectTapGestures(\n                    onTap = { onClick() },\n                    onLongPress = { onLongClick() },\n                )\n            }\n            .pointerInput(category.id, moving) {\n                if (moving) {\n                    detectHorizontalDragGestures(\n                        onDragStart = { dragAccumulator = 0f },\n                        onDragCancel = { dragAccumulator = 0f },\n                        onDragEnd = { dragAccumulator = 0f },\n                    ) { change, dragAmount ->\n                        change.consume()\n                        dragAccumulator += dragAmount\n                        while (dragAccumulator >= 18f) { onMoveRight(); dragAccumulator -= 18f }\n                        while (dragAccumulator <= -18f) { onMoveLeft(); dragAccumulator += 18f }\n                    }\n                }\n            }\n','reliable reorder gestures')
rep(main,'            .clickable(onClick = onClick, role = Role.Button)\n            .padding(horizontal = 9.dp, vertical = 6.dp),','            .padding(horizontal = 9.dp, vertical = 6.dp),','remove competing click')
rep(main,'            if (isTv) "تلميح: اضغط مطولا OK فوق الفئة، حرك بالاسهم ثم اضغط OK للحفظ" else "تلميح: اضغط مطولا على الفئة، ارفع يدك ثم اسحب يمينا او يسارا واضغطها للحفظ",','            if (isTv) "ترتيب الفئات: اضغط مطولا OK، حرك بالاسهم، ثم اضغط OK للحفظ" else "لترتيب الفئات: اضغط مطولا على الفئة، اسحبها يمينا او يسارا، ثم اضغط عليها للحفظ",','clear reorder hint')
rep(main,'            if (isTv) "تلميح: اضغط مطولا OK فوق القناة لاضافتها او ازالتها من المفضلة" else "تلميح: اضغط مطولا على القناة لاضافتها او ازالتها من المفضلة",','            if (isTv) "المفضلة: اضغط مطولا OK فوق القناة" else "المفضلة: اضغط مطولا على القناة",','clear favorite hint')
rep(main,'    val listState = rememberLazyListState(initialFirstVisibleItemIndex = rememberedIndex)\n','    val listState = rememberLazyListState(initialFirstVisibleItemIndex = rememberedIndex)\n    LaunchedEffect(listState, visible) {\n        snapshotFlow { listState.firstVisibleItemIndex }.collect { index ->\n            visible.getOrNull(index)?.let { navigationMemory.save(MainDestination.LIVE, "${it.type}:${it.id}", index) }\n        }\n    }\n','live touch scroll memory')
rep(main,'    val gridState = rememberLazyGridState(initialFirstVisibleItemIndex = targetIndex)\n    val targetRequester = remember { FocusRequester() }\n','    val gridState = rememberLazyGridState(initialFirstVisibleItemIndex = targetIndex)\n    LaunchedEffect(gridState, content, destination) {\n        snapshotFlow { gridState.firstVisibleItemIndex }.collect { index ->\n            content.getOrNull(index)?.let { navigationMemory.save(destination, "${it.type}:${it.id}", index) }\n        }\n    }\n    val targetRequester = remember { FocusRequester() }\n','content touch scroll memory')
rep(main,'    val gridState = rememberLazyGridState(initialFirstVisibleItemIndex = targetIndex)\n    val targetRequester = remember { FocusRequester() }\n','    val gridState = rememberLazyGridState(initialFirstVisibleItemIndex = targetIndex)\n    LaunchedEffect(gridState, entries, destination) {\n        snapshotFlow { gridState.firstVisibleItemIndex }.collect { index ->\n            entries.getOrNull(index)?.let { navigationMemory.save(destination, it.key, index) }\n        }\n    }\n    val targetRequester = remember { FocusRequester() }\n','history touch scroll memory')
player='app/src/main/java/sa/hulksa/player/ui/screens/PlayerScreen.kt'
rep(player,'import androidx.compose.runtime.remember\n','import androidx.compose.runtime.remember\nimport androidx.compose.runtime.rememberUpdatedState\n','updated state import')
rep(player,'    val switchRelative: (Int) -> Unit = { delta ->\n        if (channelSequence.isNotEmpty()) {\n            val currentIndex = channelSequence.indexOfFirst { it.id == request.streamId }.takeIf { it >= 0 } ?: 0\n            onSelectLiveChannel(channelSequence[relativeChannelIndex(currentIndex, delta, channelSequence.size)])\n        }\n    }\n','    val switchRelative: (Int) -> Unit = { delta ->\n        if (channelSequence.isNotEmpty()) {\n            val currentIndex = channelSequence.indexOfFirst { it.id == request.streamId }.takeIf { it >= 0 } ?: 0\n            onSelectLiveChannel(channelSequence[relativeChannelIndex(currentIndex, delta, channelSequence.size)])\n        }\n    }\n    val latestSwitchRelative by rememberUpdatedState(switchRelative)\n','latest live switch')
rep(player,'        .pointerInput(request.isLive, channelSequence) {\n            if (request.isLive) {\n                var verticalDrag = 0f\n                detectVerticalDragGestures(\n                    onVerticalDrag = { change, amount -> change.consume(); verticalDrag += amount },\n                    onDragEnd = {\n                        when {\n                            verticalDrag <= -70f -> switchRelative(1)\n                            verticalDrag >= 70f -> switchRelative(-1)\n                        }\n                        verticalDrag = 0f\n                    },\n                    onDragCancel = { verticalDrag = 0f },\n                )\n            }\n        }\n','        .pointerInput(request.isLive) {\n            if (request.isLive) {\n                var verticalDrag = 0f\n                detectVerticalDragGestures(\n                    onVerticalDrag = { change, amount -> change.consume(); verticalDrag += amount },\n                    onDragEnd = {\n                        when {\n                            verticalDrag <= -55f -> latestSwitchRelative(1)\n                            verticalDrag >= 55f -> latestSwitchRelative(-1)\n                        }\n                        verticalDrag = 0f\n                    },\n                    onDragCancel = { verticalDrag = 0f },\n                )\n            }\n        }\n','repeatable live swipe')
rep(player,'        modifier = modifier\n            .fillMaxWidth()\n            .background(Brush.verticalGradient(listOf(Color.Transparent, Color.Black.copy(alpha = .97f))))\n            .padding(horizontal = 28.dp, vertical = 22.dp),\n','        modifier = modifier\n            .fillMaxWidth()\n            .background(Brush.verticalGradient(listOf(Color.Transparent, Color.Black.copy(alpha = .97f))))\n            .navigationBarsPadding()\n            .padding(start = 12.dp, end = 12.dp, top = 10.dp, bottom = 18.dp),\n','live controls safe area')
series='app/src/main/java/sa/hulksa/player/ui/screens/SeriesScreen.kt'
rep(series,'import androidx.compose.foundation.layout.size\n','import androidx.compose.foundation.layout.size\nimport androidx.compose.foundation.layout.statusBarsPadding\n','series status import')
rep(series,'        Row(\n            Modifier.align(Alignment.TopCenter).fillMaxWidth().padding(horizontal = if (isTv) 30.dp else 15.dp, vertical = if (isTv) 22.dp else 13.dp),\n','        Row(\n            Modifier\n                .align(Alignment.TopCenter)\n                .fillMaxWidth()\n                .then(if (isTv) Modifier else Modifier.statusBarsPadding())\n                .padding(horizontal = if (isTv) 30.dp else 15.dp, vertical = if (isTv) 22.dp else 8.dp),\n','series hero safe top')
rep(series,'"الحلقة الحالية  م${episode.season} ح${episode.episodeNumber}  •  ${seriesFormatTime(entry.positionMs)}"','"الحلقة الحالية  •  الموسم ${episode.season}  •  الحلقة ${episode.episodeNumber}  •  ${seriesFormatTime(entry.positionMs)}"','series current episode label')
rep(series,'"▶ استكمال م${resumeEpisode.season} ح${resumeEpisode.episodeNumber}"','"▶ استكمال الموسم ${resumeEpisode.season} • الحلقة ${resumeEpisode.episodeNumber}"','series resume button label')
text=(root/series).read_text()
text=text.replace('"م${episode.season} • ح${episode.episodeNumber}"','"الموسم ${episode.season} • الحلقة ${episode.episodeNumber}"')
text=text.replace('"م${episode.season} ح${episode.episodeNumber}"','"الموسم ${episode.season} • الحلقة ${episode.episodeNumber}"')
(root/series).write_text(text)
print('Prepared v0.9.3.4')
