#!/usr/bin/env python3
from pathlib import Path
import sys
root=Path(sys.argv[1])

def rep(path, old, new, label):
 p=root/path; s=p.read_text()
 if new in s: return
 if old not in s: raise SystemExit(f'missing {label}')
 p.write_text(s.replace(old,new,1))

rep('app/build.gradle.kts','versionCode = 46','versionCode = 47','versionCode')
rep('app/build.gradle.kts','versionName = "0.9.3.2"','versionName = "0.9.3.3"','versionName')
main='app/src/main/java/sa/hulksa/player/ui/screens/MainShellScreen.kt'
rep(main,'import androidx.compose.foundation.gestures.detectDragGesturesAfterLongPress\n','import androidx.compose.foundation.gestures.detectHorizontalDragGestures\nimport androidx.compose.foundation.gestures.detectTapGestures\n','gesture imports')
rep(main,'import androidx.compose.runtime.mutableFloatStateOf\n','import androidx.compose.runtime.mutableFloatStateOf\nimport androidx.compose.runtime.mutableStateMapOf\n','state map import')
rep(main,'    val adaptiveUi = LocalAdaptiveUi.current\n    val useNavigationRail = adaptiveUi.navigationType == HulkNavigationType.RAIL\n','    val adaptiveUi = LocalAdaptiveUi.current\n    val useNavigationRail = adaptiveUi.navigationType == HulkNavigationType.RAIL\n    val queryMemory = remember { mutableStateMapOf<MainDestination, String>() }\n    val categoryMemory = remember { mutableStateMapOf<MainDestination, String?>() }\n    var previousDestination by remember { mutableStateOf(state.destination) }\n    LaunchedEffect(state.destination) {\n        if (previousDestination != state.destination) {\n            queryMemory[previousDestination] = state.searchQuery\n            categoryMemory[previousDestination] = state.selectedCategoryId\n            val restoredQuery = queryMemory[state.destination].orEmpty()\n            val restoredCategory = categoryMemory[state.destination]\n            if (state.searchQuery != restoredQuery) onSearch(restoredQuery)\n            if (state.selectedCategoryId != restoredCategory) onSelectCategory(restoredCategory)\n            previousDestination = state.destination\n        }\n    }\n','destination memory')
rep(main,'ReorderableLiveCategoryBar(catalog?.categories.orEmpty(), catalog?.items.orEmpty(), state.selectedCategoryId, onSelectCategory)\n        LiveInteractionHints()','ReorderableLiveCategoryBar(catalog?.categories.orEmpty(), catalog?.items.orEmpty(), state.selectedCategoryId, onSelectCategory)\n        LiveInteractionHints(isTv)','live hints arg')
rep(main,'FavoriteHint()','FavoriteHint(isTv)','favorite hint arg')
rep(main,'.pointerInput(category.id) {\n                detectDragGesturesAfterLongPress(\n                    onDragStart = {\n                        dragAccumulator = 0f\n                        onLongClick()\n                    },\n                    onDragCancel = { dragAccumulator = 0f },\n                    onDragEnd = { dragAccumulator = 0f },\n                    onDrag = { change, dragAmount ->\n                        change.consume()\n                        dragAccumulator += dragAmount.x\n                        when {\n                            dragAccumulator >= 46f -> {\n                                onMoveRight()\n                                dragAccumulator = 0f\n                            }\n                            dragAccumulator <= -46f -> {\n                                onMoveLeft()\n                                dragAccumulator = 0f\n                            }\n                        }\n                    },\n                )\n            }','.pointerInput(category.id, moving) {\n                if (moving) {\n                    detectHorizontalDragGestures(\n                        onDragStart = { dragAccumulator = 0f },\n                        onDragCancel = { dragAccumulator = 0f },\n                        onDragEnd = { dragAccumulator = 0f },\n                    ) { change, dragAmount ->\n                        change.consume()\n                        dragAccumulator += dragAmount\n                        while (dragAccumulator >= 24f) { onMoveRight(); dragAccumulator -= 24f }\n                        while (dragAccumulator <= -24f) { onMoveLeft(); dragAccumulator += 24f }\n                    }\n                } else {\n                    detectTapGestures(onLongPress = { onLongClick() })\n                }\n            }','category edit drag')
rep(main,'private fun LiveInteractionHints() {\n    val colors = LocalHulkColors.current\n    Column(Modifier.padding(horizontal = 4.dp, vertical = 2.dp)) {\n        Text(\n            "تلميح: ضغطة مطولة على OK فوق الفئة لتفعيل ترتيب الفئات",','private fun LiveInteractionHints(isTv: Boolean) {\n    val colors = LocalHulkColors.current\n    Column(Modifier.padding(horizontal = 4.dp, vertical = 2.dp)) {\n        Text(\n            if (isTv) "تلميح: اضغط مطولا OK فوق الفئة، حرك بالاسهم ثم اضغط OK للحفظ" else "تلميح: اضغط مطولا على الفئة، ارفع يدك ثم اسحب يمينا او يسارا واضغطها للحفظ",','device live hint')
rep(main,'"تلميح: ضغطة مطولة على OK فوق القناة لاضافتها او ازالتها من المفضلة",','if (isTv) "تلميح: اضغط مطولا OK فوق القناة لاضافتها او ازالتها من المفضلة" else "تلميح: اضغط مطولا على القناة لاضافتها او ازالتها من المفضلة",','channel hint')
rep(main,'private fun FavoriteHint() {\n    val colors = LocalHulkColors.current\n    Text(\n        text = "تلميح: اضغط مطولا زر OK لاضافة او ازالة العنصر من المفضلة",','private fun FavoriteHint(isTv: Boolean) {\n    val colors = LocalHulkColors.current\n    Text(\n        text = if (isTv) "تلميح: اضغط مطولا زر OK لاضافة او ازالة العنصر من المفضلة" else "تلميح: اضغط مطولا على العنصر لاضافته او ازالته من المفضلة",','favorite device hint')
player='app/src/main/java/sa/hulksa/player/ui/screens/PlayerScreen.kt'
rep(player,'import androidx.compose.foundation.gestures.detectHorizontalDragGestures\n','import androidx.compose.foundation.gestures.detectHorizontalDragGestures\nimport androidx.compose.foundation.gestures.detectVerticalDragGestures\n','vertical import')
rep(player,'    fun seekToPosition(targetMs: Long) {\n        if (request.isLive || durationMs <= 0L) return\n        val target = targetMs.coerceIn(0L, durationMs)\n        manualSeekTargetMs = target\n        currentPositionMs = target\n','    fun seekToPosition(targetMs: Long) {\n        if (request.isLive || durationMs <= 0L) return\n        val target = targetMs.coerceIn(0L, durationMs)\n        player.seekTo(target)\n        manualSeekTargetMs = target\n        currentPositionMs = target\n','immediate seek')
rep(player,'    val interactionModifier = Modifier.pointerInput(request) {\n        detectTapGestures(onTap = {\n            if (controlsLocked) {\n                unlockVisible = true\n                controlsVisible = true\n            } else {\n                controlsVisible = !controlsVisible\n            }\n        })\n    }\n','    val interactionModifier = Modifier\n        .pointerInput(request) {\n            detectTapGestures(onTap = {\n                if (controlsLocked) { unlockVisible = true; controlsVisible = true } else controlsVisible = !controlsVisible\n            })\n        }\n        .pointerInput(request.isLive, channelSequence) {\n            if (request.isLive) {\n                var verticalDrag = 0f\n                detectVerticalDragGestures(\n                    onVerticalDrag = { change, amount -> change.consume(); verticalDrag += amount },\n                    onDragEnd = {\n                        when {\n                            verticalDrag <= -70f -> switchRelative(1)\n                            verticalDrag >= 70f -> switchRelative(-1)\n                        }\n                        verticalDrag = 0f\n                    },\n                    onDragCancel = { verticalDrag = 0f },\n                )\n            }\n        }\n','live swipe')
rep(player,'        modifier = modifier\n            .fillMaxWidth()\n            .background(Brush.verticalGradient(listOf(Color.Transparent, Color.Black.copy(alpha = .97f))))\n            .padding(horizontal = 28.dp, vertical = 22.dp),\n','        modifier = modifier\n            .fillMaxWidth()\n            .background(Brush.verticalGradient(listOf(Color.Transparent, Color.Black.copy(alpha = .97f))))\n            .navigationBarsPadding()\n            .padding(horizontal = 12.dp, vertical = 10.dp),\n','live safe area')
rep(player,'Text("↑ القناة التالية  •  ↓ القناة السابقة", color = colors.textMuted, fontSize = 10.sp)','Text("اسحب لاعلى للقناة التالية  •  اسحب لاسفل للقناة السابقة", color = colors.textMuted, fontSize = 10.sp)','mobile channel hint')
rep(player,'val fraction = (offset.x / size.width.toFloat()).coerceIn(0f, 1f)\n                            onSeekTo((durationMs * fraction).toLong())','val fraction = (1f - offset.x / size.width.toFloat()).coerceIn(0f, 1f)\n                            onSeekTo((durationMs * fraction).toLong())','inverted tap seek')
rep(player,'val fraction = (change.position.x / size.width.toFloat()).coerceIn(0f, 1f)','val fraction = (1f - change.position.x / size.width.toFloat()).coerceIn(0f, 1f)','inverted drag seek')
print('Prepared v0.9.3.3')
